# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: workflow1

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy'
        required: true
        options:
        - 'dev'
        - 'qa'
        - 'uat'
        - 'prod'
        default: 'dev'
  

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow2'
